#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := yaws-sensor-bme280
EXTRA_COMPONENT_DIRS += ../components
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/../esp-idf-lib/components
include $(IDF_PATH)/make/project.mk
