#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := yaws-display
EXTRA_COMPONENT_DIRS += /home/mon/esp/yaws/components
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/../esp-idf-lib/components
include $(IDF_PATH)/make/project.mk
